// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Queue = require("bs-platform/lib/js/queue.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function run(param, onResponse) {
  var opened = /* record */[/* contents */true];
  var cancler = /* record */[/* contents : NoCancel */0];
  var cancled = /* record */[/* contents */false];
  var syncVal = /* record */[/* contents */undefined];
  var async = /* record */[/* contents */false];
  var rejection = function (err) {
    if (opened[0] && !cancled[0]) {
      return Curry._1(onResponse, /* Rejection */Block.__(0, [err]));
    } else {
      return 0;
    }
  };
  var success = function (res) {
    if (opened[0]) {
      if (async[0]) {
        var match = cancler[0];
        if (typeof match !== "number") {
          if (match.tag) {
            var fn = match[0];
            var match$1 = cancled[0];
            if (match$1) {
              Curry._1(fn, res);
            } else {
              cancler[0] = /* Cancel */Block.__(0, [(function (param) {
                      return Curry._1(fn, res);
                    })]);
            }
          }
          
        }
        
      } else {
        syncVal[0] = Caml_option.some(res);
      }
      if (cancled[0]) {
        return 0;
      } else {
        return Curry._1(onResponse, /* Success */Block.__(1, [res]));
      }
    } else {
      return 0;
    }
  };
  var intermediateCancler = Curry._2(param[0], rejection, success);
  var match = syncVal[0];
  if (match !== undefined) {
    var value = Caml_option.valFromOption(match);
    if (typeof intermediateCancler === "number" || !intermediateCancler.tag) {
      cancler[0] = intermediateCancler;
    } else {
      var fn = intermediateCancler[0];
      cancler[0] = /* Cancel */Block.__(0, [(function (param) {
              return Curry._1(fn, value);
            })]);
    }
  } else {
    async[0] = true;
    cancler[0] = intermediateCancler;
  }
  return (function (param) {
      if (cancled[0]) {
        return 0;
      } else {
        cancled[0] = true;
        var match = cancler[0];
        if (typeof match === "number") {
          opened[0] = false;
          return /* () */0;
        } else if (match.tag) {
          return /* () */0;
        } else {
          opened[0] = false;
          return Curry._1(match[0], /* () */0);
        }
      }
    });
}

function noop(param) {
  return /* () */0;
}

function chain(task, fn) {
  return /* Task */[(function (rej, res) {
              var cancelFn1 = /* record */[/* contents */noop];
              var cancelFn2 = /* record */[/* contents */noop];
              var onResponse = function (status) {
                if (status.tag) {
                  cancelFn2[0] = run(Curry._1(fn, status[0]), (function (status) {
                          if (status.tag) {
                            return Curry._1(res, status[0]);
                          } else {
                            return Curry._1(rej, status[0]);
                          }
                        }));
                  return /* () */0;
                } else {
                  return Curry._1(rej, status[0]);
                }
              };
              cancelFn1[0] = run(task, onResponse);
              return /* Cancel */Block.__(0, [(function (param) {
                            Curry._1(cancelFn1[0], /* () */0);
                            return Curry._1(cancelFn2[0], /* () */0);
                          })]);
            })];
}

function chainRec(recTask, init) {
  return /* Task */[(function (rej, res) {
              var cancelFn = /* record */[/* contents */noop];
              var currentValue = /* record */[/* contents */init];
              var async = /* record */[/* contents */false];
              var settled = /* record */[/* contents */false];
              var drain = function (param) {
                var $$break = false;
                async[0] = false;
                while(!$$break) {
                  settled[0] = false;
                  cancelFn[0] = run(Curry._1(recTask, currentValue[0]), onResponse);
                  if (!settled[0]) {
                    async[0] = true;
                    $$break = true;
                  }
                  
                };
                return /* () */0;
              };
              var onResponse = function (status) {
                if (status.tag) {
                  var value = status[0];
                  if (value.tag) {
                    return Curry._1(res, value[0]);
                  } else {
                    currentValue[0] = value[0];
                    if (async[0]) {
                      return drain(/* () */0);
                    } else {
                      settled[0] = true;
                      return /* () */0;
                    }
                  }
                } else {
                  return Curry._1(rej, status[0]);
                }
              };
              drain(/* () */0);
              return /* Cancel */Block.__(0, [(function (param) {
                            return Curry._1(cancelFn[0], /* () */0);
                          })]);
            })];
}

function chainRej(task, fn) {
  return /* Task */[(function (rej, res) {
              var cancelFn1 = /* record */[/* contents */noop];
              var cancelFn2 = /* record */[/* contents */noop];
              var onResponse = function (status) {
                if (status.tag) {
                  return Curry._1(res, status[0]);
                } else {
                  cancelFn2[0] = run(Curry._1(fn, status[0]), (function (status) {
                          if (status.tag) {
                            return Curry._1(res, status[0]);
                          } else {
                            return Curry._1(rej, status[0]);
                          }
                        }));
                  return /* () */0;
                }
              };
              cancelFn1[0] = run(task, onResponse);
              return /* Cancel */Block.__(0, [(function (param) {
                            Curry._1(cancelFn1[0], /* () */0);
                            return Curry._1(cancelFn2[0], /* () */0);
                          })]);
            })];
}

function map(task, fn) {
  return /* Task */[(function (rej, res) {
              var onResponse = function (status) {
                if (status.tag) {
                  return Curry._1(res, Curry._1(fn, status[0]));
                } else {
                  return Curry._1(rej, status[0]);
                }
              };
              var cancel = run(task, onResponse);
              return /* Cancel */Block.__(0, [cancel]);
            })];
}

function mapRej(task, fn) {
  return /* Task */[(function (rej, res) {
              var onResponse = function (status) {
                if (status.tag) {
                  return Curry._1(res, status[0]);
                } else {
                  return Curry._1(rej, Curry._1(fn, status[0]));
                }
              };
              var cancel = run(task, onResponse);
              return /* Cancel */Block.__(0, [cancel]);
            })];
}

function bimap(task, rejMap, resMap) {
  return /* Task */[(function (rej, res) {
              var onResponse = function (status) {
                if (status.tag) {
                  return Curry._1(res, Curry._1(resMap, status[0]));
                } else {
                  return Curry._1(rej, Curry._1(rejMap, status[0]));
                }
              };
              var cancel = run(task, onResponse);
              return /* Cancel */Block.__(0, [cancel]);
            })];
}

function fold(task, rejMap, resMap) {
  return /* Task */[(function (param, res) {
              var onResponse = function (status) {
                if (status.tag) {
                  return Curry._1(res, Curry._1(resMap, status[0]));
                } else {
                  return Curry._1(res, Curry._1(rejMap, status[0]));
                }
              };
              var cancel = run(task, onResponse);
              return /* Cancel */Block.__(0, [cancel]);
            })];
}

function also(task1, task2) {
  return /* Task */[(function (rej, res) {
              var cancelFn1 = /* record */[/* contents */noop];
              var cancelFn2 = /* record */[/* contents */noop];
              var onResponse = function (status) {
                if (status.tag) {
                  cancelFn2[0] = run(task2, (function (status) {
                          if (status.tag) {
                            return Curry._1(res, status[0]);
                          } else {
                            return Curry._1(rej, status[0]);
                          }
                        }));
                  return /* () */0;
                } else {
                  return Curry._1(rej, status[0]);
                }
              };
              cancelFn1[0] = run(task1, onResponse);
              return /* Cancel */Block.__(0, [(function (param) {
                            Curry._1(cancelFn1[0], /* () */0);
                            return Curry._1(cancelFn2[0], /* () */0);
                          })]);
            })];
}

function alt(task1, task2) {
  return /* Task */[(function (rej, res) {
              var cancelFn1 = /* record */[/* contents */noop];
              var cancelFn2 = /* record */[/* contents */noop];
              var onResponse = function (status) {
                if (status.tag) {
                  return Curry._1(res, status[0]);
                } else {
                  cancelFn2[0] = run(task2, (function (status) {
                          if (status.tag) {
                            return Curry._1(res, status[0]);
                          } else {
                            return Curry._1(rej, status[0]);
                          }
                        }));
                  return /* () */0;
                }
              };
              cancelFn1[0] = run(task1, onResponse);
              return /* Cancel */Block.__(0, [(function (param) {
                            Curry._1(cancelFn1[0], /* () */0);
                            return Curry._1(cancelFn2[0], /* () */0);
                          })]);
            })];
}

function $$finally(task1, task2) {
  return /* Task */[(function (rej, res) {
              var cancelFn1 = /* record */[/* contents */noop];
              var cancelFn2 = /* record */[/* contents */noop];
              var onResponse = function (status1) {
                cancelFn2[0] = run(task2, (function (status) {
                        if (status.tag) {
                          if (status1.tag) {
                            return Curry._1(res, status1[0]);
                          } else {
                            return Curry._1(rej, status1[0]);
                          }
                        } else {
                          return Curry._1(rej, status[0]);
                        }
                      }));
                return /* () */0;
              };
              cancelFn1[0] = run(task1, onResponse);
              return /* Cancel */Block.__(0, [(function (param) {
                            Curry._1(cancelFn1[0], /* () */0);
                            return Curry._1(cancelFn2[0], /* () */0);
                          })]);
            })];
}

function hook(acquire, dispose, consume) {
  return /* Task */[(function (rej, res) {
              var cancelFn1 = /* record */[/* contents */noop];
              var cancelFn2 = /* record */[/* contents */noop];
              var onAquire = function (status) {
                if (status.tag) {
                  var resource = status[0];
                  var runDispose = function (__x) {
                    return run(__x, (function (param) {
                                  if (param.tag) {
                                    return /* () */0;
                                  } else {
                                    throw param[0];
                                  }
                                }));
                  };
                  var onResponse = function (status) {
                    if (status.tag) {
                      Curry._1(res, status[0]);
                      runDispose(Curry._1(dispose, resource));
                      return /* () */0;
                    } else {
                      Curry._1(rej, status[0]);
                      runDispose(Curry._1(dispose, resource));
                      return /* () */0;
                    }
                  };
                  var cancelConsumer = run(Curry._1(consume, resource), onResponse);
                  cancelFn2[0] = (function (param) {
                      Curry._1(cancelConsumer, /* () */0);
                      runDispose(Curry._1(dispose, resource));
                      return /* () */0;
                    });
                  return /* () */0;
                } else {
                  return Curry._1(rej, status[0]);
                }
              };
              cancelFn1[0] = run(acquire, onAquire);
              return /* Cancel */Block.__(0, [(function (param) {
                            Curry._1(cancelFn1[0], /* () */0);
                            return Curry._1(cancelFn2[0], /* () */0);
                          })]);
            })];
}

function pure(value) {
  return /* Task */[(function (param, res) {
              Curry._1(res, value);
              return /* NoCancel */0;
            })];
}

function reject(value) {
  return /* Task */[(function (rej, param) {
              Curry._1(rej, value);
              return /* NoCancel */0;
            })];
}

function race(task1, task2) {
  return /* Task */[(function (rej, res) {
              var cancelTask1 = /* record */[/* contents */noop];
              var cancelTask2 = /* record */[/* contents */noop];
              cancelTask1[0] = run(task1, (function (param) {
                      if (param.tag) {
                        Curry._1(res, param[0]);
                        return Curry._1(cancelTask2[0], /* () */0);
                      } else {
                        Curry._1(rej, param[0]);
                        return Curry._1(cancelTask2[0], /* () */0);
                      }
                    }));
              cancelTask2[0] = run(task2, (function (param) {
                      if (param.tag) {
                        Curry._1(res, param[0]);
                        return Curry._1(cancelTask1[0], /* () */0);
                      } else {
                        Curry._1(rej, param[0]);
                        return Curry._1(cancelTask1[0], /* () */0);
                      }
                    }));
              return /* Cancel */Block.__(0, [(function (param) {
                            Curry._1(cancelTask1[0], /* () */0);
                            return Curry._1(cancelTask2[0], /* () */0);
                          })]);
            })];
}

function parallel(concurrentTasks) {
  return /* Task */[(function (rej, res) {
              var taskSize = List.length(concurrentTasks);
              var responses = /* record */[/* contents : array */[]];
              var hotTask = /* record */[/* contents : array */[]];
              var rejected = /* record */[/* contents */false];
              var syncQueue = Queue.create(/* () */0);
              var async = /* record */[/* contents */false];
              var onResponse = function (param) {
                if (param.tag) {
                  responses[0] = $$Array.append(responses[0], /* array */[param[0]]);
                  if (responses[0].length === taskSize) {
                    $$Array.sort((function (a, b) {
                            return a[0] - b[0] | 0;
                          }), responses[0]);
                    return Curry._1(res, $$Array.to_list($$Array.map((function (prim) {
                                          return prim[1];
                                        }), responses[0])));
                  } else {
                    return 0;
                  }
                } else {
                  $$Array.iter((function (task) {
                          return Curry._1(task[/* cancel */0], /* () */0);
                        }), hotTask[0]);
                  rejected[0] = true;
                  return Curry._1(rej, param[0]);
                }
              };
              hotTask[0] = $$Array.mapi((function (index, task) {
                      return /* record */[
                              /* cancel */run(map(task, (function (value) {
                                          return /* tuple */[
                                                  index,
                                                  value
                                                ];
                                        })), (function (value) {
                                      var match = async[0];
                                      if (match) {
                                        return onResponse(value);
                                      } else {
                                        return Queue.add(value, syncQueue);
                                      }
                                    })),
                              /* index */index
                            ];
                    }), $$Array.of_list(concurrentTasks));
              async[0] = true;
              while(!Queue.is_empty(syncQueue) && !rejected[0]) {
                onResponse(Queue.take(syncQueue));
              };
              return /* Cancel */Block.__(0, [(function (param) {
                            return $$Array.iter((function (task) {
                                          return Curry._1(task[/* cancel */0], /* () */0);
                                        }), hotTask[0]);
                          })]);
            })];
}

function both(param) {
  var task2 = param[1];
  var task1 = param[0];
  return /* Task */[(function (rej, res) {
              var task1Res = /* record */[/* contents */undefined];
              var task2Res = /* record */[/* contents */undefined];
              var task1Cancel = /* record */[/* contents */noop];
              var task2Cancel = /* record */[/* contents */noop];
              var onResponse1 = function (response) {
                if (response.tag) {
                  var value = response[0];
                  var match = task2Res[0];
                  if (match !== undefined) {
                    return Curry._1(res, /* tuple */[
                                value,
                                Caml_option.valFromOption(match)
                              ]);
                  } else {
                    task1Res[0] = Caml_option.some(value);
                    return /* () */0;
                  }
                } else {
                  Curry._1(task2Cancel[0], /* () */0);
                  return Curry._1(rej, response[0]);
                }
              };
              var onResponse2 = function (response) {
                if (response.tag) {
                  var value = response[0];
                  var match = task1Res[0];
                  if (match !== undefined) {
                    return Curry._1(res, /* tuple */[
                                Caml_option.valFromOption(match),
                                value
                              ]);
                  } else {
                    task2Res[0] = Caml_option.some(value);
                    return /* () */0;
                  }
                } else {
                  Curry._1(task1Cancel[0], /* () */0);
                  return Curry._1(rej, response[0]);
                }
              };
              task1Cancel[0] = run(task1, onResponse1);
              task2Cancel[0] = run(task2, onResponse2);
              return /* Cancel */Block.__(0, [(function (param) {
                            Curry._1(task1Cancel[0], /* () */0);
                            return Curry._1(task2Cancel[0], /* () */0);
                          })]);
            })];
}

function triple(param) {
  var task3 = param[2];
  var task2 = param[1];
  var task1 = param[0];
  return /* Task */[(function (rej, res) {
              var task1Res = /* record */[/* contents */undefined];
              var task2Res = /* record */[/* contents */undefined];
              var task1Cancel = /* record */[/* contents */noop];
              var task2Cancel = /* record */[/* contents */noop];
              var onResponse1 = function (response) {
                if (response.tag) {
                  var value = response[0];
                  var match = task2Res[0];
                  if (match !== undefined) {
                    return Curry._1(res, /* tuple */[
                                value[0],
                                value[1],
                                Caml_option.valFromOption(match)
                              ]);
                  } else {
                    task1Res[0] = value;
                    return /* () */0;
                  }
                } else {
                  Curry._1(task2Cancel[0], /* () */0);
                  return Curry._1(rej, response[0]);
                }
              };
              var onResponse2 = function (response) {
                if (response.tag) {
                  var value = response[0];
                  var match = task1Res[0];
                  if (match !== undefined) {
                    var task1Value = match;
                    return Curry._1(res, /* tuple */[
                                task1Value[0],
                                task1Value[1],
                                value
                              ]);
                  } else {
                    task2Res[0] = Caml_option.some(value);
                    return /* () */0;
                  }
                } else {
                  Curry._1(task1Cancel[0], /* () */0);
                  return Curry._1(rej, response[0]);
                }
              };
              task1Cancel[0] = run(both(/* tuple */[
                        task1,
                        task2
                      ]), onResponse1);
              task2Cancel[0] = run(task3, onResponse2);
              return /* Cancel */Block.__(0, [(function (param) {
                            Curry._1(task1Cancel[0], /* () */0);
                            return Curry._1(task2Cancel[0], /* () */0);
                          })]);
            })];
}

function quadruple(param) {
  var task4 = param[3];
  var task3 = param[2];
  var task2 = param[1];
  var task1 = param[0];
  return /* Task */[(function (rej, res) {
              var task1Res = /* record */[/* contents */undefined];
              var task2Res = /* record */[/* contents */undefined];
              var task1Cancel = /* record */[/* contents */noop];
              var task2Cancel = /* record */[/* contents */noop];
              var onResponse1 = function (response) {
                if (response.tag) {
                  var value = response[0];
                  var match = task2Res[0];
                  if (match !== undefined) {
                    var task2Value = match;
                    return Curry._1(res, /* tuple */[
                                value[0],
                                value[1],
                                task2Value[0],
                                task2Value[1]
                              ]);
                  } else {
                    task1Res[0] = value;
                    return /* () */0;
                  }
                } else {
                  Curry._1(task2Cancel[0], /* () */0);
                  return Curry._1(rej, response[0]);
                }
              };
              var onResponse2 = function (response) {
                if (response.tag) {
                  var value = response[0];
                  var match = task1Res[0];
                  if (match !== undefined) {
                    var task1Value = match;
                    return Curry._1(res, /* tuple */[
                                task1Value[0],
                                task1Value[1],
                                value[0],
                                value[1]
                              ]);
                  } else {
                    task2Res[0] = value;
                    return /* () */0;
                  }
                } else {
                  Curry._1(task1Cancel[0], /* () */0);
                  return Curry._1(rej, response[0]);
                }
              };
              task1Cancel[0] = run(both(/* tuple */[
                        task1,
                        task2
                      ]), onResponse1);
              task2Cancel[0] = run(both(/* tuple */[
                        task3,
                        task4
                      ]), onResponse2);
              return /* Cancel */Block.__(0, [(function (param) {
                            Curry._1(task1Cancel[0], /* () */0);
                            return Curry._1(task2Cancel[0], /* () */0);
                          })]);
            })];
}

function quintuple(param) {
  var task5 = param[4];
  var task4 = param[3];
  var task3 = param[2];
  var task2 = param[1];
  var task1 = param[0];
  return /* Task */[(function (rej, res) {
              var task1Res = /* record */[/* contents */undefined];
              var task2Res = /* record */[/* contents */undefined];
              var task1Cancel = /* record */[/* contents */noop];
              var task2Cancel = /* record */[/* contents */noop];
              var onResponse1 = function (response) {
                if (response.tag) {
                  var value = response[0];
                  var match = task2Res[0];
                  if (match !== undefined) {
                    return Curry._1(res, /* tuple */[
                                value[0],
                                value[1],
                                value[2],
                                value[3],
                                Caml_option.valFromOption(match)
                              ]);
                  } else {
                    task1Res[0] = value;
                    return /* () */0;
                  }
                } else {
                  Curry._1(task2Cancel[0], /* () */0);
                  return Curry._1(rej, response[0]);
                }
              };
              var onResponse2 = function (response) {
                if (response.tag) {
                  var value = response[0];
                  var match = task1Res[0];
                  if (match !== undefined) {
                    var task1Value = match;
                    return Curry._1(res, /* tuple */[
                                task1Value[0],
                                task1Value[1],
                                task1Value[2],
                                task1Value[3],
                                value
                              ]);
                  } else {
                    task2Res[0] = Caml_option.some(value);
                    return /* () */0;
                  }
                } else {
                  Curry._1(task1Cancel[0], /* () */0);
                  return Curry._1(rej, response[0]);
                }
              };
              task1Cancel[0] = run(quadruple(/* tuple */[
                        task1,
                        task2,
                        task3,
                        task4
                      ]), onResponse1);
              task2Cancel[0] = run(task5, onResponse2);
              return /* Cancel */Block.__(0, [(function (param) {
                            Curry._1(task1Cancel[0], /* () */0);
                            return Curry._1(task2Cancel[0], /* () */0);
                          })]);
            })];
}

function sextuple(param) {
  var task6 = param[5];
  var task5 = param[4];
  var task4 = param[3];
  var task3 = param[2];
  var task2 = param[1];
  var task1 = param[0];
  return /* Task */[(function (rej, res) {
              var task1Res = /* record */[/* contents */undefined];
              var task2Res = /* record */[/* contents */undefined];
              var task1Cancel = /* record */[/* contents */noop];
              var task2Cancel = /* record */[/* contents */noop];
              var onResponse1 = function (response) {
                if (response.tag) {
                  var value = response[0];
                  var match = task2Res[0];
                  if (match !== undefined) {
                    return Curry._1(res, /* tuple */[
                                value[0],
                                value[1],
                                value[2],
                                value[3],
                                value[4],
                                Caml_option.valFromOption(match)
                              ]);
                  } else {
                    task1Res[0] = value;
                    return /* () */0;
                  }
                } else {
                  Curry._1(task2Cancel[0], /* () */0);
                  return Curry._1(rej, response[0]);
                }
              };
              var onResponse2 = function (response) {
                if (response.tag) {
                  var value = response[0];
                  var match = task1Res[0];
                  if (match !== undefined) {
                    var task1Value = match;
                    return Curry._1(res, /* tuple */[
                                task1Value[0],
                                task1Value[1],
                                task1Value[2],
                                task1Value[3],
                                task1Value[4],
                                value
                              ]);
                  } else {
                    task2Res[0] = Caml_option.some(value);
                    return /* () */0;
                  }
                } else {
                  Curry._1(task1Cancel[0], /* () */0);
                  return Curry._1(rej, response[0]);
                }
              };
              task1Cancel[0] = run(quintuple(/* tuple */[
                        task1,
                        task2,
                        task3,
                        task4,
                        task5
                      ]), onResponse1);
              task2Cancel[0] = run(task6, onResponse2);
              return /* Cancel */Block.__(0, [(function (param) {
                            Curry._1(task1Cancel[0], /* () */0);
                            return Curry._1(task2Cancel[0], /* () */0);
                          })]);
            })];
}

var Operators = /* module */[
  /* >>= */chain,
  /* >>| */map,
  /* >>=! */chainRej,
  /* >>|! */mapRej,
  /* >>> */run
];

var bind = chain;

var resolve = pure;

exports.run = run;
exports.noop = noop;
exports.chain = chain;
exports.bind = bind;
exports.chainRec = chainRec;
exports.chainRej = chainRej;
exports.map = map;
exports.mapRej = mapRej;
exports.bimap = bimap;
exports.fold = fold;
exports.also = also;
exports.alt = alt;
exports.$$finally = $$finally;
exports.hook = hook;
exports.pure = pure;
exports.resolve = resolve;
exports.reject = reject;
exports.race = race;
exports.parallel = parallel;
exports.both = both;
exports.triple = triple;
exports.quadruple = quadruple;
exports.quintuple = quintuple;
exports.sextuple = sextuple;
exports.Operators = Operators;
/* No side effect */
