// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Task$Task = require("./Task.bs.js");

function encaseP(promiseFn, param) {
  return /* Task */[(function (rej, res) {
              Curry._1(promiseFn, param).then((function (pResp) {
                        return Promise.resolve(Curry._1(res, pResp));
                      })).catch((function (error) {
                      return Promise.resolve(Curry._1(rej, error));
                    }));
              return /* NoCancel */0;
            })];
}

function encaseP2(promiseFn, param1, param2) {
  return /* Task */[(function (rej, res) {
              Curry._2(promiseFn, param1, param2).then((function (pResp) {
                        return Promise.resolve(Curry._1(res, pResp));
                      })).catch((function (error) {
                      return Promise.resolve(Curry._1(rej, error));
                    }));
              return /* NoCancel */0;
            })];
}

function encaseP3(promiseFn, param1, param2, param3) {
  return /* Task */[(function (rej, res) {
              Curry._3(promiseFn, param1, param2, param3).then((function (pResp) {
                        return Promise.resolve(Curry._1(res, pResp));
                      })).catch((function (error) {
                      return Promise.resolve(Curry._1(rej, error));
                    }));
              return /* NoCancel */0;
            })];
}

function toPromise(task) {
  return new Promise((function (resolve, param) {
                Task$Task.run((function (value) {
                        return resolve(value);
                      }), task);
                return /* () */0;
              }));
}

function after(wait, value) {
  return /* Task */[(function (param, res) {
              var timer = setTimeout((function (param) {
                      return Curry._1(res, value);
                    }), wait);
              return /* Cancel */[(function (param) {
                          clearTimeout(timer);
                          return /* () */0;
                        })];
            })];
}

function rejectAfter(wait, value) {
  return /* Task */[(function (rej, param) {
              var timer = setTimeout((function (param) {
                      return Curry._1(rej, value);
                    }), wait);
              return /* Cancel */[(function (param) {
                          clearTimeout(timer);
                          return /* () */0;
                        })];
            })];
}

exports.encaseP = encaseP;
exports.encaseP2 = encaseP2;
exports.encaseP3 = encaseP3;
exports.toPromise = toPromise;
exports.after = after;
exports.rejectAfter = rejectAfter;
/* No side effect */
